use circle ci as cicd server

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -2,8 +2,9 @@
 
 set -Eeuo pipefail
 
-RELEASER_VERSION="2.1.0"
-DOCKER_OPS_VERSION="2.0.0"
+RELEASER_VERSION="2.1.3"
+DOCKER_OPS_VERSION="2.0.1
+setup_github_credentials"
 SECRET_OPS_VERSION="0.8.0"
 
 SECRET_OPS_FILE="ops/secret-ops"
@@ -30,6 +31,21 @@ image_name="kudulab/golang-dojo"
 image_registry="dockerhub"
 image_dir="./image"
 imagerc_filename="imagerc"
+
+function setup_github_credentials {
+  if [ -z "$GITHUB_CREDENTIALS" ]; then
+    echo "Error: GITHUB_CREDENTIALS not set" >&2
+    exit 1
+  fi
+  # GITHUB_CREDENTIALS should be in format of account-name:api-key
+
+  # example HTTPS URL: https://github.com/user/repo.git
+  # example SSH URL: git@github.com:user/repo.git
+  OLD_URL=$(git remote get-url origin)
+  NEW_URL=$(echo $OLD_URL | sed "s|git@github.com:|https://$GITHUB_CREDENTIALS@github.com/|g")
+  git remote set-url origin $NEW_URL
+  echo "GitHub new remote was set"
+}
 
 command="$1"
 case "${command}" in
@@ -69,6 +85,7 @@ case "${command}" in
       ;;
   release)
       ./tasks verify_version
+      setup_github_credentials
       releaser::git_tag_from_changelog
       ;;
   publish)
