use circle ci as cicd server

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -46,6 +46,20 @@ function setup_github_credentials {
   echo "GitHub new remote was set"
 }
 
+function docker_login {
+  if [ -n "$DOCKERHUB_TOKEN" ]; then
+    echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+    return
+  fi
+  echo "Warning: docker environment variables not found: falling back to Vault for authentication." >&2
+  vault_user_path=$USER
+  if [ $vault_user_path == "go" ]; then
+    vault_user_path="gocd"
+  fi
+  dockerhub_user=$(vault read -field=user secret/$vault_user_path/dockerhub)
+  vault read -field=password secret/$vault_user_path/dockerhub | docker login --username $dockerhub_user --password-stdin
+}
+
 command="$1"
 case "${command}" in
   set_version)
@@ -60,7 +74,7 @@ case "${command}" in
       docker_ops::docker_build "${image_dir}" "${imagerc_filename}" "${image_name}" "${image_tag}" "${image_registry}"
       ;;
   build)
-      secret_ops::docker_login
+      docker_login
       ./tasks build_local
       docker_ops::push "${image_dir}" "${imagerc_filename}"
       ;;
